In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

np.random.seed(42)
n=100000
start_date = datetime(2023,1,1)
dates = [start_date + timedelta(days=int(np.random.randint(0,650))) for _ in range(n)]

df = pd.DataFrame({
    'Transaction_ID': [f'TXN{1000000+i}' for i in range(n)],
    'Date': dates,
    'Customer_ID': [f'CUST{int(np.random.randint(1000,9999))}' for _ in range(n)],
    'Age': np.random.randint(18,75,n),
    'Account_Type': np.random.choice(['Savings','Checking','Credit','Loan'], n, p=[0.4,0.35,0.15,0.1]),
    'Transaction_Type': np.random.choice(['Deposit','Withdrawal','Transfer','Payment','Purchase'], n),
    'Amount': np.round(np.random.exponential(500, n) + 10, 2),
    'Branch': np.random.choice(['Hamilton Downtown','Toronto Main','Oakville','Burlington','Mississauga'], n),
    'Channel': np.random.choice(['Online','ATM','In-Branch','Mobile App'], n),
    'Balance_After': np.round(np.random.uniform(100, 50000, n), 2),
    'Is_Fraud': np.random.choice([0,1], n, p=[0.98,0.02])
})

df.to_csv('project2_banking_100k.csv', index=False)
print("100k ready!")

100k ready!

In [2]:
import pandas as pd

In [3]:
df.head()

,Transaction_ID,Date,Customer_ID,Age,Account_Type,Transaction_Type,Amount,Branch,Channel,Balance_After,Is_Fraud
0,TXN1000000,2023-04-13,CUST6035,21,Credit,Withdrawal,60.58,Toronto Main,Online,45912.17,0
1,TXN1000001,2024-03-11,CUST5111,73,Savings,Purchase,874.56,Hamilton Downtown,ATM,16186.09,0
2,TXN1000002,2023-09-28,CUST3506,61,Savings,Deposit,426.58,Hamilton Downtown,In-Branch,13457.55,0
3,TXN1000003,2023-04-17,CUST3032,57,Credit,Purchase,228.29,Mississauga,Mobile App,9263.26,0
4,TXN1000004,2023-03-13,CUST8117,59,Credit,Deposit,1072.84,Hamilton Downtown,Mobile App,34522.61,0

In [4]:
df.describe()

,Date,Age,Amount,Balance_After,Is_Fraud
count,100000,100000.000000,100000.000000,100000.000000,100000.000000
mean,2023-11-21 09:29:28.608000,46.010260,509.326618,25029.944918,0.019920
min,2023-01-01 00:00:00,18.000000,10.000000,100.160000,0.000000
25%,2023-06-12 00:00:00,32.000000,154.700000,12555.162500,0.000000
50%,2023-11-21 00:00:00,46.000000,357.250000,25054.845000,0.000000
75%,2024-05-03 00:00:00,60.000000,701.735000,37437.742500,0.000000
max,2024-10-11 00:00:00,74.000000,5828.960000,49999.160000,1.000000
std,NaN,16.451222,497.335698,14395.981405,0.139726

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction_ID    100000 non-null  object
 1   Date              100000 non-null  datetime64[ns]
 2   Customer_ID       100000 non-null  object
 3   Age               100000 non-null  int32
 4   Account_Type      100000 non-null  object
 5   Transaction_Type  100000 non-null  object
 6   Amount            100000 non-null  float64
 7   Branch            100000 non-null  object
 8   Channel           100000 non-null  object
 9   Balance_After     100000 non-null  float64
 10  Is_Fraud          100000 non-null  int64
dtypes: datetime64[ns](1), float64(2), int32(1), int64(1), object(6)
memory usage: 8.0+ MB

In [6]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

np.random.seed(42)
n=100000
start_date = datetime(2023,1,1)
dates = [start_date + timedelta(days=int(np.random.randint(0,650))) for _ in range(n)]

df = pd.DataFrame({
    'Transaction_ID': [f'TXN{1000000+i}' for i in range(n)],
    'Date': dates,
    'Customer_ID': [f'CUST{int(np.random.randint(1000,9999))}' for _ in range(n)],
    'Customer_Name': np.random.choice(['John Smith',' Priya Patel ','AHMED ALI','emily johnson','  David Lee'], n),
    'Age': np.random.randint(18,75,n).astype(object),
    'Account_Type': np.random.choice(['Savings','savings','SAVINGS','Checking','CHECKING','Credit','Loan'], n),
    'Transaction_Type': np.random.choice(['Deposit','deposits','Withdrawal','WITHDRAWAL','Transfer','Payment'], n),
    'Amount': np.round(np.random.exponential(500, n) + 10, 2).astype(object),
    'Branch': np.random.choice(['Hamilton Downtown',' hamilton downtown ','Toronto Main','TORONTO MAIN','Oakville', None], n, p=[0.3,0.1,0.3,0.05,0.2,0.05]),
    'Channel': np.random.choice(['Online','online','ATM','In-Branch',' Mobile App '], n),
    'Balance_After': np.round(np.random.uniform(100, 50000, n), 2),
    'Is_Fraud': np.random.choice([0,1,'Yes','No'], n, p=[0.49,0.01,0.25,0.25])
})

# REAL MESS
df.loc[np.random.choice(n, 4500, False), 'Amount'] = np.nan
df.loc[np.random.choice(n, 3200, False), 'Age'] = np.nan
df.loc[np.random.choice(n, 800, False), 'Amount'] = -500
df.loc[np.random.choice(n, 300, False), 'Age'] = 200
df.loc[np.random.choice(n, 50, False), 'Amount'] = 150000
df.loc[np.random.choice(n, 700, False), 'Date'] = '2023-13-45'
dupes = df.sample(800)
df = pd.concat([df, dupes], ignore_index=True)

df.to_csv('project2_REAL_MESSY_100k.csv', index=False)
print("Messy file created:", len(df))
print(df.isnull().sum())

C:\Users\riyab\AppData\Local\Temp\ipykernel_28172\834080563.py:31: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2023-13-45' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  df.loc[np.random.choice(n, 700, False), 'Date'] = '2023-13-45'

Messy file created: 100800
Transaction_ID         0
Date                   0
Customer_ID            0
Customer_Name          0
Age                 3203
Account_Type           0
Transaction_Type       0
Amount              4497
Branch              5158
Channel                0
Balance_After          0
Is_Fraud               0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100800 entries, 0 to 100799
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction_ID    100800 non-null  object
 1   Date              100800 non-null  object
 2   Customer_ID       100800 non-null  object
 3   Customer_Name     100800 non-null  object
 4   Age               97597 non-null   object
 5   Account_Type      100800 non-null  object
 6   Transaction_Type  100800 non-null  object
 7   Amount            96303 non-null   object
 8   Branch            95642 non-null   object
 9   Channel           100800 non-null  object
 10  Balance_After     100800 non-null  float64
 11  Is_Fraud          100800 non-null  object
dtypes: float64(1), object(11)
memory usage: 9.2+ MB

In [8]:
df.head(50)

,Transaction_ID,Date,Customer_ID,Customer_Name,Age,Account_Type,Transaction_Type,Amount,Branch,Channel,Balance_After,Is_Fraud
0,TXN1000000,2023-04-13 00:00:00,CUST6035,emily johnson,44,CHECKING,Deposit,252.46,Toronto Main,online,26802.96,No
1,TXN1000001,2024-03-11 00:00:00,CUST5111,emily johnson,73,CHECKING,deposits,51.33,Hamilton Downtown,Online,43790.93,0
2,TXN1000002,2023-09-28 00:00:00,CUST3506,Priya Patel,43,CHECKING,deposits,381.18,Oakville,Online,5457.91,0
3,TXN1000003,2023-04-17 00:00:00,CUST3032,AHMED ALI,27,savings,WITHDRAWAL,28.28,hamilton downtown,Online,44349.10,0
4,TXN1000004,2023-03-13 00:00:00,CUST8117,Priya Patel,57,Checking,Deposit,855.34,Hamilton Downtown,Mobile App,41369.47,0
5,TXN1000005,2023-01-21 00:00:00,CUST2147,AHMED ALI,72,savings,WITHDRAWAL,84.07,Oakville,In-Branch,7102.67,No
6,TXN1000006,2024-09-06 00:00:00,CUST3592,John Smith,27,Checking,deposits,1007.37,hamilton downtown,online,6821.65,Yes
7,TXN1000007,2023-05-02 00:00:00,CUST7663,emily johnson,53,CHECKING,Withdrawal,185.49,Hamilton Downtown,Online,3344.22,No
8,TXN1000008,2024-04-11 00:00:00,CUST7888,Priya Patel,55,Checking,WITHDRAWAL,267.29,Hamilton Downtown,online,23799.00,0
9,TXN1000009,2023-08-03 00:00:00,CUST4875,AHMED ALI,69,Credit,Payment,NaN,hamilton downtown,Online,41128.65,Yes
10,TXN1000010,2023-11-27 00:00:00,CUST7502,John Smith,59,CHECKING,Payment,930.26,hamilton downtown,In-Branch,48853.53,0
11,TXN1000011,2024-04-03 00:00:00,CUST2748,John Smith,21,Credit,Deposit,88.16,hamilton downtown,online,7019.84,No
12,TXN1000012,2023-03-29 00:00:00,CUST6968,AHMED ALI,43,Loan,Withdrawal,-500,Toronto Main,Mobile App,14887.85,0
13,TXN1000013,2024-01-08 00:00:00,CUST5646,John Smith,42,SAVINGS,Payment,66.96,hamilton downtown,Mobile App,39599.15,Yes
14,TXN1000014,2023-04-10 00:00:00,CUST4190,David Lee,48,Checking,Transfer,555.22,None,ATM,25243.60,Yes
15,TXN1000015,2023-05-11 00:00:00,CUST9628,John Smith,62,Loan,Deposit,429.15,Toronto Main,In-Branch,22016.91,1
16,TXN1000016,2023-11-05 00:00:00,CUST2512,AHMED ALI,54,SAVINGS,Deposit,691.8,Toronto Main,Mobile App,37851.31,No
17,TXN1000017,2023-12-10 00:00:00,CUST4107,emily johnson,20,Loan,Transfer,428.21,Toronto Main,Online,23182.86,0
18,TXN1000018,2024-05-06 00:00:00,CUST1502,AHMED ALI,52,Savings,deposits,2364.56,Toronto Main,Mobile App,43964.17,0
19,TXN1000019,2024-02-18 00:00:00,CUST8428,Priya Patel,63,CHECKING,Deposit,1520.9,Oakville,Online,38668.57,0
20,TXN1000020,2024-01-21 00:00:00,CUST1323,David Lee,NaN,Savings,deposits,125.11,TORONTO MAIN,In-Branch,31266.79,Yes
21,TXN1000021,2023-07-11 00:00:00,CUST2952,emily johnson,38,Savings,Payment,1752.25,Toronto Main,Mobile App,2679.03,0
22,TXN1000022,2023-10-04 00:00:00,CUST5664,David Lee,51,Credit,Deposit,473.66,Toronto Main,Mobile App,29840.38,0
23,TXN1000023,2023-06-10 00:00:00,CUST8347,AHMED ALI,31,Loan,Withdrawal,350.96,hamilton downtown,In-Branch,6955.59,0
24,TXN1000024,2024-04-04 00:00:00,CUST3370,John Smith,24,Savings,WITHDRAWAL,115.95,Hamilton Downtown,online,37354.20,Yes
25,TXN1000025,2023-11-10 00:00:00,CUST3503,AHMED ALI,74,Credit,WITHDRAWAL,40.57,Oakville,Mobile App,41079.94,0
26,TXN1000026,2023-01-22 00:00:00,CUST3582,Priya Patel,42,Savings,WITHDRAWAL,1426.57,Hamilton Downtown,Mobile App,17321.39,No
27,TXN1000027,2023-09-10 00:00:00,CUST9474,David Lee,34,savings,Withdrawal,491.36,Toronto Main,Online,34391.63,0
28,TXN1000028,2024-07-14 00:00:00,CUST1417,Priya Patel,65,Checking,deposits,273.8,hamilton downtown,online,41148.39,0
29,TXN1000029,2024-04-19 00:00:00,CUST5288,Priya Patel,56,Loan,deposits,786.98,Toronto Main,Mobile App,33937.70,0
30,TXN1000030,2023-02-28 00:00:00,CUST5616,David Lee,21,Checking,Transfer,191.9,Oakville,In-Branch,40480.33,0
31,TXN1000031,2024-05-25 00:00:00,CUST6874,David Lee,24,Savings,Deposit,929.79,Oakville,online,19765.45,No
32,TXN1000032,2024-04-20 00:00:00,CUST1536,emily johnson,50,Checking,Withdrawal,89.23,Toronto Main,In-Branch,45581.11,No
33,TXN1000033,2023-07-09 00:00:00,CUST8569,emily johnson,61,Checking,Payment,1576.34,Hamilton Downtown,In-Branch,41639.35,Yes
34,TXN1000034,2024-07-16 00:00:00,CUST2014,David Lee,66,Credit,Payment,417.71,Hamilton Downtown,ATM,789.78,0
35,TXN1000035,2024-07-20 00:00:00,CUST5336,emily johnson,67,SAVINGS,WITHDRAWAL,421.16,Oakville,In-Branch,4776.56,0
36,TXN1000036,2023-09-01 00:00:00,CUST1282,AHMED ALI,36,CHECKING,Withdrawal,987.35,Toronto Main,Online,23297.22,Yes
37,TXN1000037,2024-05-19 00:00:00,CUST8688,Priya Patel,37,CHECKING,Payment,881.32,Oakville,online,32741.30,0
38,TXN1000038,2023-05-11 00:00:00,CUST5811,Priya Patel,73,CHECKING,Transfer,347.59,Toronto Main,online,12141.25,0
39,TXN1000039,2024-04-29 00:00:00,CUST8282,John Smith,38,Checking,Payment,109.41,Toronto Main,online,12194.70,Yes
40,TXN1000040,2024-10-08 00:00:00,CUST3094,David Lee,25,Savings,deposits,39.38,hamilton downtown,Online,30888.17,0
41,TXN1000041,2023-01-21 00:00:00,CUST7993,David Lee,60,savings,Deposit,16.45,Toronto Main,ATM,20414.88,No
42,TXN1000042,2023-06-16 00:00:00,CUST9890,John Smith,25,Checking,WITHDRAWAL,124.3,Oakville,Online,48887.69,0
43,TXN1000043,2023-10-01 00:00:00,CUST4072,Priya Patel,24,CHECKING,deposits,357.72,None,Mobile App,19841.03,No
44,TXN1000044,2024-01-23 00:00:00,CUST5294,Priya Patel,56,CHECKING,deposits,218.61,Toronto Main,online,34847.56,0
45,TXN1000045,2024-08-23 00:00:00,CUST7508,John Smith,24,Credit,Transfer,55.44,hamilton downtown,ATM,32465.06,No
46,TXN1000046,2023-11-12 00:00:00,CUST9787,AHMED ALI,49,CHECKING,Deposit,762.32,Toronto Main,Mobile App,7784.33,No
47,TXN1000047,2023-01-14 00:00:00,CUST7591,John Smith,59,Checking,WITHDRAWAL,120.38,Hamilton Downtown,In-Branch,17691.75,Yes
48,TXN1000048,2023-08-30 00:00:00,CUST9027,AHMED ALI,71,CHECKING,Withdrawal,1855.56,hamilton downtown,In-Branch,37167.44,Yes
49,TXN1000049,2023-12-12 00:00:00,CUST7166,John Smith,NaN,SAVINGS,WITHDRAWAL,49.42,Oakville,In-Branch,40067.39,Yes

In [9]:
#astype(str) means make everything in that column as string first
df['Customer_Name']=df['Customer_Name'].astype(str).str.title().str.strip()

In [10]:
df.duplicated().sum()

np.int64(800)

In [11]:
df=df.drop_duplicates(subset=['Transaction_ID'],keep='first')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction_ID    100000 non-null  object
 1   Date              100000 non-null  object
 2   Customer_ID       100000 non-null  object
 3   Customer_Name     100000 non-null  object
 4   Age               96811 non-null   object
 5   Account_Type      100000 non-null  object
 6   Transaction_Type  100000 non-null  object
 7   Amount            95541 non-null   object
 8   Branch            94881 non-null   object
 9   Channel           100000 non-null  object
 10  Balance_After     100000 non-null  float64
 11  Is_Fraud          100000 non-null  object
dtypes: float64(1), object(11)
memory usage: 9.9+ MB

In [13]:
df['Date']=pd.to_datetime(df['Date'],errors='coerce')

In [14]:
df=df.copy()

In [15]:
type(df)

pandas.core.frame.DataFrame

In [16]:
df['Age']=pd.to_numeric(df['Age'], errors='coerce')

In [17]:
df['Amount']=df['Amount'].astype(str).str.replace('$','',regex=False).str.replace(',','',regex=False)

In [18]:
df['Amount'].unique()[:10]

array(['252.46', '51.33', '381.18', '28.28', '855.34', '84.07', '1007.37',
       '185.49', '267.29', 'nan'], dtype=object)

In [19]:
df['Amount']=pd.to_numeric(df['Amount'], errors='coerce')

In [20]:
df['Amount'].dtype

dtype('float64')

In [21]:
df['Is_Fraud'].unique()

array(['No', '0', 'Yes', '1'], dtype=object)

In [22]:
df['Is_Fraud']=df['Is_Fraud'].astype(str).str.strip().str.lower().map({'yes':True,'no':False,'1':True,'0':False})

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction_ID    100000 non-null  object
 1   Date              99300 non-null   datetime64[ns]
 2   Customer_ID       100000 non-null  object
 3   Customer_Name     100000 non-null  object
 4   Age               96811 non-null   float64
 5   Account_Type      100000 non-null  object
 6   Transaction_Type  100000 non-null  object
 7   Amount            95541 non-null   float64
 8   Branch            94881 non-null   object
 9   Channel           100000 non-null  object
 10  Balance_After     100000 non-null  float64
 11  Is_Fraud          100000 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(3), object(7)
memory usage: 9.3+ MB

In [24]:
df['Age']=df['Age'].fillna(df['Age'].median())

In [25]:
df['Amount']=df['Amount'].fillna(df['Amount'].median())

In [26]:
df['Branch']=df['Branch'].fillna(df['Branch'].mode()[0])

In [27]:
df=df.dropna(subset=['Date'])

In [28]:
df.shape

(99300, 12)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99300 entries, 0 to 99999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    99300 non-null  object
 1   Date              99300 non-null  datetime64[ns]
 2   Customer_ID       99300 non-null  object
 3   Customer_Name     99300 non-null  object
 4   Age               99300 non-null  float64
 5   Account_Type      99300 non-null  object
 6   Transaction_Type  99300 non-null  object
 7   Amount            99300 non-null  float64
 8   Branch            99300 non-null  object
 9   Channel           99300 non-null  object
 10  Balance_After     99300 non-null  float64
 11  Is_Fraud          99300 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(3), object(7)
memory usage: 9.2+ MB

In [30]:
df['Account_Type'].unique()

array(['CHECKING', 'savings', 'Checking', 'Credit', 'Loan', 'SAVINGS',
       'Savings'], dtype=object)

In [31]:
df['Transaction_Type'].unique()

array(['Deposit', 'deposits', 'WITHDRAWAL', 'Withdrawal', 'Payment',
       'Transfer'], dtype=object)

In [32]:
df['Branch']=df['Branch'].astype(str).str.strip().str.title()

In [33]:
df['Channel']=df['Channel'].astype(str).str.strip().str.title()

In [34]:
df['Account_Type']=df['Account_Type'].astype(str).str.strip().str.title()

In [35]:
df['Transaction_Type']=df['Transaction_Type'].astype(str).str.strip().str.title().str.replace('Deposits','Deposit',regex=False)

In [36]:
df[df['Amount']<0]

,Transaction_ID,Date,Customer_ID,Customer_Name,Age,Account_Type,Transaction_Type,Amount,Branch,Channel,Balance_After,Is_Fraud
12,TXN1000012,2023-03-29,CUST6968,Ahmed Ali,43.0,Loan,Withdrawal,-500.0,Toronto Main,Mobile App,14887.85,False
84,TXN1000084,2023-06-06,CUST7862,David Lee,73.0,Savings,Deposit,-500.0,Hamilton Downtown,In-Branch,517.07,False
256,TXN1000256,2023-09-11,CUST7113,Ahmed Ali,24.0,Savings,Transfer,-500.0,Oakville,In-Branch,10442.15,False
559,TXN1000559,2023-06-22,CUST4853,John Smith,19.0,Savings,Transfer,-500.0,Oakville,Online,5378.03,True
937,TXN1000937,2024-04-22,CUST9797,Emily Johnson,51.0,Savings,Payment,-500.0,Toronto Main,Mobile App,7367.74,False
...,...,...,...,...,...,...,...,...,...,...,...,...
99533,TXN1099533,2023-11-20,CUST7023,Emily Johnson,52.0,Savings,Transfer,-500.0,Oakville,Online,43530.76,False
99601,TXN1099601,2024-04-24,CUST4846,David Lee,39.0,Credit,Withdrawal,-500.0,Toronto Main,Mobile App,48801.55,True
99652,TXN1099652,2023-08-08,CUST3424,Priya Patel,32.0,Checking,Transfer,-500.0,Toronto Main,Mobile App,17291.51,False
99725,TXN1099725,2024-03-30,CUST3602,Emily Johnson,28.0,Checking,Withdrawal,-500.0,Toronto Main,Online,49033.08,False
99841,TXN1099841,2024-07-05,CUST6588,David Lee,46.0,Savings,Deposit,-500.0,Toronto Main,In-Branch,17715.09,False

In [37]:
df['Amount']=df['Amount'].abs()

In [38]:
df[df['Age']>100]

,Transaction_ID,Date,Customer_ID,Customer_Name,Age,Account_Type,Transaction_Type,Amount,Branch,Channel,Balance_After,Is_Fraud
755,TXN1000755,2023-01-08,CUST6983,David Lee,200.0,Credit,Deposit,431.50,Oakville,Online,13435.62,False
1027,TXN1001027,2023-06-28,CUST7293,Ahmed Ali,200.0,Savings,Transfer,34.23,Oakville,Mobile App,4493.51,False
1138,TXN1001138,2023-04-25,CUST1946,Emily Johnson,200.0,Savings,Deposit,97.74,Hamilton Downtown,In-Branch,19393.82,True
1847,TXN1001847,2024-09-13,CUST7750,Priya Patel,200.0,Savings,Deposit,371.89,Hamilton Downtown,In-Branch,14763.14,False
2095,TXN1002095,2023-04-27,CUST1160,John Smith,200.0,Loan,Transfer,1101.87,Hamilton Downtown,In-Branch,19662.94,False
...,...,...,...,...,...,...,...,...,...,...,...,...
98569,TXN1098569,2023-08-10,CUST3803,John Smith,200.0,Loan,Payment,84.69,Toronto Main,Online,38550.89,False
98860,TXN1098860,2024-10-03,CUST5323,Priya Patel,200.0,Loan,Deposit,353.76,Hamilton Downtown,Atm,42681.10,False
98908,TXN1098908,2024-05-10,CUST3994,Ahmed Ali,200.0,Savings,Withdrawal,2662.30,Hamilton Downtown,Atm,7195.43,False
99166,TXN1099166,2024-09-13,CUST8513,Ahmed Ali,200.0,Savings,Deposit,616.07,Toronto Main,Atm,24655.48,False
99227,TXN1099227,2023-01-09,CUST4351,John Smith,200.0,Credit,Payment,311.67,Oakville,Mobile App,37606.74,False

In [39]:
df=df[(df['Age']>=18) & (df['Age']<=100)]

In [40]:
df.shape

(99002, 12)

In [41]:
df.isnull().sum()

Transaction_ID      0
Date                0
Customer_ID         0
Customer_Name       0
Age                 0
Account_Type        0
Transaction_Type    0
Amount              0
Branch              0
Channel             0
Balance_After       0
Is_Fraud            0
dtype: int64

In [42]:
df['Age'].min()

18.0

In [43]:
df.describe()

,Date,Age,Amount,Balance_After
count,99002,99002.000000,99002.000000,99002.000000
mean,2023-11-21 09:29:37.927718656,46.009293,577.016764,25054.906489
min,2023-01-01 00:00:00,18.000000,10.000000,100.320000
25%,2023-06-12 00:00:00,32.000000,164.392500,12528.275000
50%,2023-11-21 00:00:00,46.000000,353.760000,25099.590000
75%,2024-05-03 00:00:00,60.000000,674.870000,37561.952500
max,2024-10-11 00:00:00,74.000000,150000.000000,49999.350000
std,NaN,16.186458,3360.434042,14422.238038

In [44]:
df['Age']=df['Age'].astype(int)

In [45]:
df=df.copy()

In [46]:
df['Age'].dtype

dtype('int64')

In [47]:
# STEP 1: Check Age - in simple numbers
print("--- AGE CHECK ---")
Q1_age = df['Age'].quantile(0.25)
Q3_age = df['Age'].quantile(0.75)
IQR_age = Q3_age - Q1_age

print(f"Q1 (25%): {Q1_age}")
print(f"Q3 (75%): {Q3_age}")
print(f"IQR (middle spread): {IQR_age}")

# STEP 2: Calculate normal range
lower_age = Q1_age - 1.5 * IQR_age
upper_age = Q3_age + 1.5 * IQR_age

print(f"\nNormal Age should be between {lower_age:.1f} and {upper_age:.1f}")

# STEP 3: Find weird ages
weird_age = df[(df['Age'] < lower_age) | (df['Age'] > upper_age)]
print(f"\nFound {len(weird_age)} weird Age rows")
print(weird_age[['Age', 'Branch', 'Amount']].head(10))

# STEP 4: Same for Amount - to catch fraud
print("\n--- AMOUNT CHECK (Fraud Check) ---")
Q1_amt = df['Amount'].quantile(0.25)
Q3_amt = df['Amount'].quantile(0.75)
IQR_amt = Q3_amt - Q1_amt

lower_amt = Q1_amt - 1.5 * IQR_amt
upper_amt = Q3_amt + 1.5 * IQR_amt

print(f"Normal Amount should be between {lower_amt:.1f} and {upper_amt:.1f}")

weird_amount = df[df['Amount'] > upper_amt]  # only high amount is fraud
print(f"\nFound {len(weird_amount)} high Amount (possible fraud) rows")
print(weird_amount[['Age', 'Branch', 'Amount', 'Transaction_Type']].head(10))

--- AGE CHECK ---
Q1 (25%): 32.0
Q3 (75%): 60.0
IQR (middle spread): 28.0

Normal Age should be between -10.0 and 102.0

Found 0 weird Age rows
Empty DataFrame
Columns: [Age, Branch, Amount]
Index: []

--- AMOUNT CHECK (Fraud Check) ---
Normal Amount should be between -601.3 and 1440.6

Found 5429 high Amount (possible fraud) rows
    Age             Branch   Amount Transaction_Type
18   52       Toronto Main  2364.56          Deposit
19   63           Oakville  1520.90          Deposit
21   38       Toronto Main  1752.25          Payment
33   61  Hamilton Downtown  1576.34          Payment
48   71  Hamilton Downtown  1855.56       Withdrawal
54   57  Hamilton Downtown  1617.85         Transfer
60   42       Toronto Main  1934.86       Withdrawal
62   18       Toronto Main  1569.83       Withdrawal
71   50  Hamilton Downtown  1576.32         Transfer
80   38  Hamilton Downtown  1546.15          Deposit

In [58]:
import sqlite3

In [51]:
df.to_csv('Project2_banking_cleaned_Final.csv', index=False)

In [66]:
df=pd.read_csv('Project2_banking_cleaned_Final.csv')

In [69]:
conn=sqlite3.connect('Banking_project_cleaned.db')
df.to_sql('banking_transaction',conn,if_exists='replace',index=False)

99002

In [70]:
q1=pd.read_sql("select count(*)as Total_Transaction From banking_transaction",conn)

In [73]:
print(q1)

   Total_Transaction
0              99002

In [77]:
q2=pd.read_sql("select Branch,Count(*) as Total_brn_ct From banking_transaction group by Branch ",conn)

In [75]:
print(q2)

              Branch  Total_brn_ct
0  Hamilton Downtown         44743
1           Oakville         19595
2       Toronto Main         34664

In [78]:
q3=pd.read_sql("select Channel,count(*)as Fraud From banking_transaction where Is_Fraud=1 Group By Channel",conn)

In [79]:
print(q3)

      Channel  Fraud
0         Atm   5181
1   In-Branch   5122
2  Mobile App   5095
3      Online  10308

In [80]:
q4=pd.read_sql("Select Transaction_type, sum(Amount) as Total_Amount, count(*) as Total_txn From banking_transaction Group By Transaction_type",conn )

In [81]:
print(q4)

  Transaction_Type  Total_Amount  Total_txn
0          Deposit   18614109.88      32883
1          Payment    9263749.63      16394
2         Transfer    9875222.24      16560
3       Withdrawal   19372731.94      33165

In [84]:
q4_fraud=pd.read_sql("""select transaction_type, count(*)as Fraud_count,Sum(Amount)as fraud_amt 
                     From banking_transaction 
                     where Is_fraud=1 
                     group by Transaction_type""",conn)

In [83]:
print(q4_fraud)

  Transaction_Type  Fraud_count   fraud_amt
0          Deposit         8499  4755544.02
1          Payment         4246  2585742.44
2         Transfer         4304  2468333.14
3       Withdrawal         8657  5194116.23

In [85]:
q4_channel_fraud=pd.read_sql("""select channel,transaction_type, count(*)as Fraud_count,Sum(Amount)as fraud_amt 
                     From banking_transaction 
                     where Is_fraud=1 
                     group by Channel,Transaction_type
                             order by Fraud_count DESC""",conn)

In [86]:
print(q4_channel_fraud)

       Channel Transaction_Type  Fraud_count   fraud_amt
0       Online          Deposit         3439  1884340.45
1       Online       Withdrawal         3437  2307123.26
2   Mobile App       Withdrawal         1769   866316.82
3          Atm       Withdrawal         1727  1015663.90
4          Atm          Deposit         1725   895972.61
5    In-Branch       Withdrawal         1724  1005012.25
6       Online          Payment         1724  1031291.42
7       Online         Transfer         1708  1020373.39
8    In-Branch          Deposit         1704   884099.99
9   Mobile App          Deposit         1631  1091130.97
10         Atm         Transfer          910   440944.49
11  Mobile App          Payment          857   574297.46
12   In-Branch         Transfer          848   443144.93
13   In-Branch          Payment          846   436219.27
14  Mobile App         Transfer          838   563870.33
15         Atm          Payment          819   543934.29

In [90]:
q_velocity_final = pd.read_sql("""
SELECT 
  d.Customer_ID,
  d.Date as Deposit_Time,
  w.Date as Withdrawal_Time,
  CAST((JULIANDAY(w.Date) - JULIANDAY(d.Date)) as INTEGER) as Days_Diff,
  d.Amount as Deposit_Amt,
  w.Amount as Withdrawal_Amt
FROM banking_transaction d
JOIN banking_transaction w 
  ON d.Customer_ID = w.Customer_ID
  AND w.Date > d.Date
WHERE d.Transaction_Type = 'Deposit'
  AND w.Transaction_Type = 'Withdrawal'
  AND (JULIANDAY(w.Date) - JULIANDAY(d.Date)) <= 7
ORDER BY Days_Diff ASC
LIMIT 20
""", conn)

In [91]:
print(q_velocity_final)

   Customer_ID Deposit_Time Withdrawal_Time  Days_Diff  Deposit_Amt  \
0     CUST1733   2023-02-08      2023-02-09          1       181.39
1     CUST4243   2024-02-03      2024-02-04          1       132.76
2     CUST9971   2023-12-28      2023-12-29          1      1569.47
3     CUST9666   2023-01-23      2023-01-24          1       353.48
4     CUST6437   2023-07-06      2023-07-07          1        74.40
5     CUST5969   2024-08-11      2024-08-12          1       389.63
6     CUST2178   2023-07-30      2023-07-31          1       321.15
7     CUST8318   2023-08-11      2023-08-12          1      1049.10
8     CUST9534   2023-08-16      2023-08-17          1       345.47
9     CUST3844   2023-12-02      2023-12-03          1       663.19
10    CUST3576   2023-08-12      2023-08-13          1       353.76
11    CUST1128   2023-11-26      2023-11-27          1       503.21
12    CUST9728   2024-02-01      2024-02-02          1       352.58
13    CUST8880   2024-04-08      2024-04-09          1       122.69
14    CUST4807   2023-10-16      2023-10-17          1       737.87
15    CUST3980   2023-07-12      2023-07-13          1      1753.07
16    CUST3809   2024-07-21      2024-07-22          1       460.10
17    CUST1413   2023-05-24      2023-05-25          1       226.48
18    CUST5483   2023-04-02      2023-04-03          1        72.37
19    CUST2060   2023-04-14      2023-04-15          1       284.63

    Withdrawal_Amt
0           983.06
1           500.00
2           110.56
3           634.22
4          1257.53
5           634.20
6           544.73
7           322.65
8           353.76
9           795.60
10          607.51
11           18.47
12          198.11
13           57.18
14           38.62
15          324.39
16          443.69
17          369.33
18          558.99
19          126.79

In [92]:
q_rule = pd.read_sql("""
SELECT 
  Channel,
  Transaction_Type,
  COUNT(*) as Flagged_Txn,
  SUM(Amount) as Blocked_Amount,
  ROUND(AVG(Amount),2) as Avg_Fraud_Amount
FROM banking_transaction
WHERE Is_Fraud = 1
  AND Channel = 'Online'
  AND Amount > 500
GROUP BY Channel, Transaction_Type
""", conn)

print(q_rule)

  Channel Transaction_Type  Flagged_Txn  Blocked_Amount  Avg_Fraud_Amount
0  Online          Deposit         1222      1363230.81           1115.57
1  Online          Payment          627       776145.53           1237.87
2  Online         Transfer          613       776075.54           1266.03
3  Online       Withdrawal         1222      1805441.26           1477.45

In [93]:
Risk_Measure=pd.read_sql("""SELECT 
                        case when Amount<500 THEN 'small'
                        when Amount Between 500 and 5000 then 'Medium'
                        Else 'Large(>5K)-Flag'
                        End as risk_bucket,
                         count(*)as tx_count,
                         sum(case when is_fraud=1 then Amount else 0 End)as fraud_amount
                         From Banking_transaction
                         Group by risk_bucket
                         order by fraud_amount Desc""",conn)

In [94]:
print(Risk_Measure)

       risk_bucket  tx_count  fraud_amount
0           Medium     35978    9212984.03
1            small     62970    3690751.80
2  Large(>5K)-Flag        54    2100000.00

In [96]:
Risk_flags=pd.read_sql("""SELECT
  t.*,
  -- q3
  CASE WHEN Channel='Online' AND Is_Fraud=1 THEN 1 ELSE 0 END as is_online_fraud,
  -- q4_fraud
  CASE WHEN Transaction_Type='Withdrawal' AND Is_Fraud=1 THEN 1 ELSE 0 END as is_withdrawal_fraud,
  -- q4_channel_fraud (your $2.3M top risk)
  CASE WHEN Channel='Online' AND Transaction_Type='Withdrawal' AND Is_Fraud=1 THEN 1 ELSE 0 END as is_online_withdrawal_fraud,
  CASE WHEN Channel='Online' AND Transaction_Type='Deposit' AND Is_Fraud=1 THEN 1 ELSE 0 END as is_online_deposit_fraud,
  -- q_rule (3,684 = $4.7M)
  CASE WHEN Channel='Online' AND Amount>500 AND Is_Fraud=1 THEN 1 ELSE 0 END as q_rule_flag,
  -- Risk_Measure (Large 54)
  CASE WHEN Amount<500 THEN 'small' WHEN Amount<=5000 THEN 'Medium' ELSE 'Large(>5K)-Flag' END as risk_bucket
FROM banking_transaction t""",conn)

In [97]:
print(Risk_flags)

      Transaction_ID        Date Customer_ID  Customer_Name  Age Account_Type  \
0         TXN1000000  2023-04-13    CUST6035  Emily Johnson   44     Checking
1         TXN1000001  2024-03-11    CUST5111  Emily Johnson   73     Checking
2         TXN1000002  2023-09-28    CUST3506    Priya Patel   43     Checking
3         TXN1000003  2023-04-17    CUST3032      Ahmed Ali   27      Savings
4         TXN1000004  2023-03-13    CUST8117    Priya Patel   57     Checking
...              ...         ...         ...            ...  ...          ...
98997     TXN1099995  2023-03-06    CUST7168  Emily Johnson   52         Loan
98998     TXN1099996  2024-02-23    CUST5351     John Smith   55      Savings
98999     TXN1099997  2024-10-09    CUST9827  Emily Johnson   66     Checking
99000     TXN1099998  2024-10-09    CUST1156      Ahmed Ali   29     Checking
99001     TXN1099999  2024-06-23    CUST7964     John Smith   58      Savings

      Transaction_Type   Amount             Branch     Channel  Balance_After  \
0              Deposit   252.46       Toronto Main      Online       26802.96
1              Deposit    51.33  Hamilton Downtown      Online       43790.93
2              Deposit   381.18           Oakville      Online        5457.91
3           Withdrawal    28.28  Hamilton Downtown      Online       44349.10
4              Deposit   855.34  Hamilton Downtown  Mobile App       41369.47
...                ...      ...                ...         ...            ...
98997         Transfer   202.34       Toronto Main      Online       38606.83
98998         Transfer   181.53       Toronto Main      Online       26203.83
98999          Deposit  1291.19           Oakville   In-Branch       12029.68
99000       Withdrawal   297.89       Toronto Main  Mobile App        8321.00
99001       Withdrawal   481.30           Oakville         Atm       33427.61

       Is_Fraud  is_online_fraud  is_withdrawal_fraud  \
0             0                0                    0
1             0                0                    0
2             0                0                    0
3             0                0                    0
4             0                0                    0
...         ...              ...                  ...
98997         1                1                    0
98998         0                0                    0
98999         0                0                    0
99000         0                0                    0
99001         0                0                    0

       is_online_withdrawal_fraud  is_online_deposit_fraud  q_rule_flag  \
0                               0                        0            0
1                               0                        0            0
2                               0                        0            0
3                               0                        0            0
4                               0                        0            0
...                           ...                      ...          ...
98997                           0                        0            0
98998                           0                        0            0
98999                           0                        0            0
99000                           0                        0            0
99001                           0                        0            0

      risk_bucket
0           small
1           small
2           small
3           small
4          Medium
...           ...
98997       small
98998       small
98999      Medium
99000       small
99001       small

[99002 rows x 18 columns]

In [98]:
Risk_flags.to_csv('risk_view.csv',index=False)

In [99]:
print(Risk_flags['q_rule_flag'].sum())

3684

In [100]:
print(Risk_flags['risk_bucket'].value_counts())

risk_bucket
small              62970
Medium             35978
Large(>5K)-Flag       54
Name: count, dtype: int64

In [101]:
print(Risk_flags['is_online_withdrawal_fraud'].sum())

3437

In [102]:
q_velocity_final.to_csv('q_velocity.csv',index=False)